version: "3.8"

services:
  web:
    build: ./web
    command: sleep infinity 
    volumes:
      - ./web:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - minio
    env_file:
      - .env.dev
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mercado
      POSTGRES_PASSWORD: mercado
      POSTGRES_DB: mercado
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO web konsolu
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  worker:
    build: ./web
    command: sleep infinity   
    depends_on:
      - redis
      - db
    env_file:
      - .env.dev
    restart: unless-stopped

  beat:
    build: ./web
    command: sleep infinity      
    depends_on:
      - redis
      - db
    env_file:
      - .env.dev
    restart: unless-stopped

volumes:
  db_data:
  minio_data:
